# Generated by Django 6.0.2 on 2026-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_remove_socio_direccion_socio_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
