# Generated by Django 6.0.2 on 2026-02-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='condicion',
            field=models.CharField(choices=[('normal', 'Activo'), ('excedencia', 'Excedencia'), ('protector', 'Protector')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo',
            field=models.CharField(choices=[('adulto', 'Adulto'), ('cadete', 'Cadete'), ('infantil', 'Infantil')], default='adulto', max_length=20),
            preserve_default=False,
        ),
    ]
