# Generated by Django 6.0.2 on 2026-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_socio_condicion_socio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_festero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Festero'),
        ),
    ]
