# Generated by Django 6.0.2 on 2026-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_condicion_tiposocio_alter_socio_condicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='numero_festero',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nº Festero'),
        ),
    ]
