# Generated by Django 6.0.2 on 2026-02-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_alter_socio_numero_festero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='socios.condicion'),
        ),
    ]
