# Generated by Django 6.0.2 on 2026-02-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_alter_socio_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicion',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='socios.tiposocio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socio',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.condicion'),
        ),
    ]
