# Generated by Django 6.0.2 on 2026-02-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_condicion_tipo_alter_socio_condicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicion',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='socio',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='socios.condicion'),
        ),
    ]
