# Generated by Django 6.0.2 on 2026-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0011_condicion_tipo_alter_socio_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposocio',
            name='requiere_condicion',
            field=models.BooleanField(default=False, help_text='Si este tipo necesita condición obligatoria'),
        ),
    ]
